require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CargoEleicaosController do

  # This should return the minimal set of attributes required to create a valid
  # CargoEleicao. As you add validations to CargoEleicao, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CargoEleicaosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all cargo_eleicaos as @cargo_eleicaos" do
      cargo_eleicao = CargoEleicao.create! valid_attributes
      get :index, {}, valid_session
      assigns(:cargo_eleicaos).should eq([cargo_eleicao])
    end
  end

  describe "GET show" do
    it "assigns the requested cargo_eleicao as @cargo_eleicao" do
      cargo_eleicao = CargoEleicao.create! valid_attributes
      get :show, {:id => cargo_eleicao.to_param}, valid_session
      assigns(:cargo_eleicao).should eq(cargo_eleicao)
    end
  end

  describe "GET new" do
    it "assigns a new cargo_eleicao as @cargo_eleicao" do
      get :new, {}, valid_session
      assigns(:cargo_eleicao).should be_a_new(CargoEleicao)
    end
  end

  describe "GET edit" do
    it "assigns the requested cargo_eleicao as @cargo_eleicao" do
      cargo_eleicao = CargoEleicao.create! valid_attributes
      get :edit, {:id => cargo_eleicao.to_param}, valid_session
      assigns(:cargo_eleicao).should eq(cargo_eleicao)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CargoEleicao" do
        expect {
          post :create, {:cargo_eleicao => valid_attributes}, valid_session
        }.to change(CargoEleicao, :count).by(1)
      end

      it "assigns a newly created cargo_eleicao as @cargo_eleicao" do
        post :create, {:cargo_eleicao => valid_attributes}, valid_session
        assigns(:cargo_eleicao).should be_a(CargoEleicao)
        assigns(:cargo_eleicao).should be_persisted
      end

      it "redirects to the created cargo_eleicao" do
        post :create, {:cargo_eleicao => valid_attributes}, valid_session
        response.should redirect_to(CargoEleicao.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cargo_eleicao as @cargo_eleicao" do
        # Trigger the behavior that occurs when invalid params are submitted
        CargoEleicao.any_instance.stub(:save).and_return(false)
        post :create, {:cargo_eleicao => {}}, valid_session
        assigns(:cargo_eleicao).should be_a_new(CargoEleicao)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CargoEleicao.any_instance.stub(:save).and_return(false)
        post :create, {:cargo_eleicao => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cargo_eleicao" do
        cargo_eleicao = CargoEleicao.create! valid_attributes
        # Assuming there are no other cargo_eleicaos in the database, this
        # specifies that the CargoEleicao created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CargoEleicao.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => cargo_eleicao.to_param, :cargo_eleicao => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested cargo_eleicao as @cargo_eleicao" do
        cargo_eleicao = CargoEleicao.create! valid_attributes
        put :update, {:id => cargo_eleicao.to_param, :cargo_eleicao => valid_attributes}, valid_session
        assigns(:cargo_eleicao).should eq(cargo_eleicao)
      end

      it "redirects to the cargo_eleicao" do
        cargo_eleicao = CargoEleicao.create! valid_attributes
        put :update, {:id => cargo_eleicao.to_param, :cargo_eleicao => valid_attributes}, valid_session
        response.should redirect_to(cargo_eleicao)
      end
    end

    describe "with invalid params" do
      it "assigns the cargo_eleicao as @cargo_eleicao" do
        cargo_eleicao = CargoEleicao.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CargoEleicao.any_instance.stub(:save).and_return(false)
        put :update, {:id => cargo_eleicao.to_param, :cargo_eleicao => {}}, valid_session
        assigns(:cargo_eleicao).should eq(cargo_eleicao)
      end

      it "re-renders the 'edit' template" do
        cargo_eleicao = CargoEleicao.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CargoEleicao.any_instance.stub(:save).and_return(false)
        put :update, {:id => cargo_eleicao.to_param, :cargo_eleicao => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cargo_eleicao" do
      cargo_eleicao = CargoEleicao.create! valid_attributes
      expect {
        delete :destroy, {:id => cargo_eleicao.to_param}, valid_session
      }.to change(CargoEleicao, :count).by(-1)
    end

    it "redirects to the cargo_eleicaos list" do
      cargo_eleicao = CargoEleicao.create! valid_attributes
      delete :destroy, {:id => cargo_eleicao.to_param}, valid_session
      response.should redirect_to(cargo_eleicaos_url)
    end
  end

end
