require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ColigacaoPartidosController do

  # This should return the minimal set of attributes required to create a valid
  # ColigacaoPartido. As you add validations to ColigacaoPartido, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ColigacaoPartidosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all coligacao_partidos as @coligacao_partidos" do
      coligacao_partido = ColigacaoPartido.create! valid_attributes
      get :index, {}, valid_session
      assigns(:coligacao_partidos).should eq([coligacao_partido])
    end
  end

  describe "GET show" do
    it "assigns the requested coligacao_partido as @coligacao_partido" do
      coligacao_partido = ColigacaoPartido.create! valid_attributes
      get :show, {:id => coligacao_partido.to_param}, valid_session
      assigns(:coligacao_partido).should eq(coligacao_partido)
    end
  end

  describe "GET new" do
    it "assigns a new coligacao_partido as @coligacao_partido" do
      get :new, {}, valid_session
      assigns(:coligacao_partido).should be_a_new(ColigacaoPartido)
    end
  end

  describe "GET edit" do
    it "assigns the requested coligacao_partido as @coligacao_partido" do
      coligacao_partido = ColigacaoPartido.create! valid_attributes
      get :edit, {:id => coligacao_partido.to_param}, valid_session
      assigns(:coligacao_partido).should eq(coligacao_partido)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ColigacaoPartido" do
        expect {
          post :create, {:coligacao_partido => valid_attributes}, valid_session
        }.to change(ColigacaoPartido, :count).by(1)
      end

      it "assigns a newly created coligacao_partido as @coligacao_partido" do
        post :create, {:coligacao_partido => valid_attributes}, valid_session
        assigns(:coligacao_partido).should be_a(ColigacaoPartido)
        assigns(:coligacao_partido).should be_persisted
      end

      it "redirects to the created coligacao_partido" do
        post :create, {:coligacao_partido => valid_attributes}, valid_session
        response.should redirect_to(ColigacaoPartido.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved coligacao_partido as @coligacao_partido" do
        # Trigger the behavior that occurs when invalid params are submitted
        ColigacaoPartido.any_instance.stub(:save).and_return(false)
        post :create, {:coligacao_partido => {}}, valid_session
        assigns(:coligacao_partido).should be_a_new(ColigacaoPartido)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ColigacaoPartido.any_instance.stub(:save).and_return(false)
        post :create, {:coligacao_partido => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested coligacao_partido" do
        coligacao_partido = ColigacaoPartido.create! valid_attributes
        # Assuming there are no other coligacao_partidos in the database, this
        # specifies that the ColigacaoPartido created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ColigacaoPartido.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => coligacao_partido.to_param, :coligacao_partido => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested coligacao_partido as @coligacao_partido" do
        coligacao_partido = ColigacaoPartido.create! valid_attributes
        put :update, {:id => coligacao_partido.to_param, :coligacao_partido => valid_attributes}, valid_session
        assigns(:coligacao_partido).should eq(coligacao_partido)
      end

      it "redirects to the coligacao_partido" do
        coligacao_partido = ColigacaoPartido.create! valid_attributes
        put :update, {:id => coligacao_partido.to_param, :coligacao_partido => valid_attributes}, valid_session
        response.should redirect_to(coligacao_partido)
      end
    end

    describe "with invalid params" do
      it "assigns the coligacao_partido as @coligacao_partido" do
        coligacao_partido = ColigacaoPartido.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ColigacaoPartido.any_instance.stub(:save).and_return(false)
        put :update, {:id => coligacao_partido.to_param, :coligacao_partido => {}}, valid_session
        assigns(:coligacao_partido).should eq(coligacao_partido)
      end

      it "re-renders the 'edit' template" do
        coligacao_partido = ColigacaoPartido.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ColigacaoPartido.any_instance.stub(:save).and_return(false)
        put :update, {:id => coligacao_partido.to_param, :coligacao_partido => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested coligacao_partido" do
      coligacao_partido = ColigacaoPartido.create! valid_attributes
      expect {
        delete :destroy, {:id => coligacao_partido.to_param}, valid_session
      }.to change(ColigacaoPartido, :count).by(-1)
    end

    it "redirects to the coligacao_partidos list" do
      coligacao_partido = ColigacaoPartido.create! valid_attributes
      delete :destroy, {:id => coligacao_partido.to_param}, valid_session
      response.should redirect_to(coligacao_partidos_url)
    end
  end

end
