require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ColigacaosController do

  # This should return the minimal set of attributes required to create a valid
  # Coligacao. As you add validations to Coligacao, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ColigacaosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all coligacaos as @coligacaos" do
      coligacao = Coligacao.create! valid_attributes
      get :index, {}, valid_session
      assigns(:coligacaos).should eq([coligacao])
    end
  end

  describe "GET show" do
    it "assigns the requested coligacao as @coligacao" do
      coligacao = Coligacao.create! valid_attributes
      get :show, {:id => coligacao.to_param}, valid_session
      assigns(:coligacao).should eq(coligacao)
    end
  end

  describe "GET new" do
    it "assigns a new coligacao as @coligacao" do
      get :new, {}, valid_session
      assigns(:coligacao).should be_a_new(Coligacao)
    end
  end

  describe "GET edit" do
    it "assigns the requested coligacao as @coligacao" do
      coligacao = Coligacao.create! valid_attributes
      get :edit, {:id => coligacao.to_param}, valid_session
      assigns(:coligacao).should eq(coligacao)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Coligacao" do
        expect {
          post :create, {:coligacao => valid_attributes}, valid_session
        }.to change(Coligacao, :count).by(1)
      end

      it "assigns a newly created coligacao as @coligacao" do
        post :create, {:coligacao => valid_attributes}, valid_session
        assigns(:coligacao).should be_a(Coligacao)
        assigns(:coligacao).should be_persisted
      end

      it "redirects to the created coligacao" do
        post :create, {:coligacao => valid_attributes}, valid_session
        response.should redirect_to(Coligacao.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved coligacao as @coligacao" do
        # Trigger the behavior that occurs when invalid params are submitted
        Coligacao.any_instance.stub(:save).and_return(false)
        post :create, {:coligacao => {}}, valid_session
        assigns(:coligacao).should be_a_new(Coligacao)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Coligacao.any_instance.stub(:save).and_return(false)
        post :create, {:coligacao => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested coligacao" do
        coligacao = Coligacao.create! valid_attributes
        # Assuming there are no other coligacaos in the database, this
        # specifies that the Coligacao created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Coligacao.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => coligacao.to_param, :coligacao => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested coligacao as @coligacao" do
        coligacao = Coligacao.create! valid_attributes
        put :update, {:id => coligacao.to_param, :coligacao => valid_attributes}, valid_session
        assigns(:coligacao).should eq(coligacao)
      end

      it "redirects to the coligacao" do
        coligacao = Coligacao.create! valid_attributes
        put :update, {:id => coligacao.to_param, :coligacao => valid_attributes}, valid_session
        response.should redirect_to(coligacao)
      end
    end

    describe "with invalid params" do
      it "assigns the coligacao as @coligacao" do
        coligacao = Coligacao.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Coligacao.any_instance.stub(:save).and_return(false)
        put :update, {:id => coligacao.to_param, :coligacao => {}}, valid_session
        assigns(:coligacao).should eq(coligacao)
      end

      it "re-renders the 'edit' template" do
        coligacao = Coligacao.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Coligacao.any_instance.stub(:save).and_return(false)
        put :update, {:id => coligacao.to_param, :coligacao => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested coligacao" do
      coligacao = Coligacao.create! valid_attributes
      expect {
        delete :destroy, {:id => coligacao.to_param}, valid_session
      }.to change(Coligacao, :count).by(-1)
    end

    it "redirects to the coligacaos list" do
      coligacao = Coligacao.create! valid_attributes
      delete :destroy, {:id => coligacao.to_param}, valid_session
      response.should redirect_to(coligacaos_url)
    end
  end

end
