require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EleicaosController do

  # This should return the minimal set of attributes required to create a valid
  # Eleicao. As you add validations to Eleicao, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EleicaosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all eleicaos as @eleicaos" do
      eleicao = Eleicao.create! valid_attributes
      get :index, {}, valid_session
      assigns(:eleicaos).should eq([eleicao])
    end
  end

  describe "GET show" do
    it "assigns the requested eleicao as @eleicao" do
      eleicao = Eleicao.create! valid_attributes
      get :show, {:id => eleicao.to_param}, valid_session
      assigns(:eleicao).should eq(eleicao)
    end
  end

  describe "GET new" do
    it "assigns a new eleicao as @eleicao" do
      get :new, {}, valid_session
      assigns(:eleicao).should be_a_new(Eleicao)
    end
  end

  describe "GET edit" do
    it "assigns the requested eleicao as @eleicao" do
      eleicao = Eleicao.create! valid_attributes
      get :edit, {:id => eleicao.to_param}, valid_session
      assigns(:eleicao).should eq(eleicao)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Eleicao" do
        expect {
          post :create, {:eleicao => valid_attributes}, valid_session
        }.to change(Eleicao, :count).by(1)
      end

      it "assigns a newly created eleicao as @eleicao" do
        post :create, {:eleicao => valid_attributes}, valid_session
        assigns(:eleicao).should be_a(Eleicao)
        assigns(:eleicao).should be_persisted
      end

      it "redirects to the created eleicao" do
        post :create, {:eleicao => valid_attributes}, valid_session
        response.should redirect_to(Eleicao.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved eleicao as @eleicao" do
        # Trigger the behavior that occurs when invalid params are submitted
        Eleicao.any_instance.stub(:save).and_return(false)
        post :create, {:eleicao => {}}, valid_session
        assigns(:eleicao).should be_a_new(Eleicao)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Eleicao.any_instance.stub(:save).and_return(false)
        post :create, {:eleicao => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested eleicao" do
        eleicao = Eleicao.create! valid_attributes
        # Assuming there are no other eleicaos in the database, this
        # specifies that the Eleicao created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Eleicao.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => eleicao.to_param, :eleicao => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested eleicao as @eleicao" do
        eleicao = Eleicao.create! valid_attributes
        put :update, {:id => eleicao.to_param, :eleicao => valid_attributes}, valid_session
        assigns(:eleicao).should eq(eleicao)
      end

      it "redirects to the eleicao" do
        eleicao = Eleicao.create! valid_attributes
        put :update, {:id => eleicao.to_param, :eleicao => valid_attributes}, valid_session
        response.should redirect_to(eleicao)
      end
    end

    describe "with invalid params" do
      it "assigns the eleicao as @eleicao" do
        eleicao = Eleicao.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Eleicao.any_instance.stub(:save).and_return(false)
        put :update, {:id => eleicao.to_param, :eleicao => {}}, valid_session
        assigns(:eleicao).should eq(eleicao)
      end

      it "re-renders the 'edit' template" do
        eleicao = Eleicao.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Eleicao.any_instance.stub(:save).and_return(false)
        put :update, {:id => eleicao.to_param, :eleicao => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested eleicao" do
      eleicao = Eleicao.create! valid_attributes
      expect {
        delete :destroy, {:id => eleicao.to_param}, valid_session
      }.to change(Eleicao, :count).by(-1)
    end

    it "redirects to the eleicaos list" do
      eleicao = Eleicao.create! valid_attributes
      delete :destroy, {:id => eleicao.to_param}, valid_session
      response.should redirect_to(eleicaos_url)
    end
  end

end
