require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EnderecosController do

  # This should return the minimal set of attributes required to create a valid
  # Endereco. As you add validations to Endereco, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EnderecosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all enderecos as @enderecos" do
      endereco = Endereco.create! valid_attributes
      get :index, {}, valid_session
      assigns(:enderecos).should eq([endereco])
    end
  end

  describe "GET show" do
    it "assigns the requested endereco as @endereco" do
      endereco = Endereco.create! valid_attributes
      get :show, {:id => endereco.to_param}, valid_session
      assigns(:endereco).should eq(endereco)
    end
  end

  describe "GET new" do
    it "assigns a new endereco as @endereco" do
      get :new, {}, valid_session
      assigns(:endereco).should be_a_new(Endereco)
    end
  end

  describe "GET edit" do
    it "assigns the requested endereco as @endereco" do
      endereco = Endereco.create! valid_attributes
      get :edit, {:id => endereco.to_param}, valid_session
      assigns(:endereco).should eq(endereco)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Endereco" do
        expect {
          post :create, {:endereco => valid_attributes}, valid_session
        }.to change(Endereco, :count).by(1)
      end

      it "assigns a newly created endereco as @endereco" do
        post :create, {:endereco => valid_attributes}, valid_session
        assigns(:endereco).should be_a(Endereco)
        assigns(:endereco).should be_persisted
      end

      it "redirects to the created endereco" do
        post :create, {:endereco => valid_attributes}, valid_session
        response.should redirect_to(Endereco.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved endereco as @endereco" do
        # Trigger the behavior that occurs when invalid params are submitted
        Endereco.any_instance.stub(:save).and_return(false)
        post :create, {:endereco => {}}, valid_session
        assigns(:endereco).should be_a_new(Endereco)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Endereco.any_instance.stub(:save).and_return(false)
        post :create, {:endereco => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested endereco" do
        endereco = Endereco.create! valid_attributes
        # Assuming there are no other enderecos in the database, this
        # specifies that the Endereco created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Endereco.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => endereco.to_param, :endereco => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested endereco as @endereco" do
        endereco = Endereco.create! valid_attributes
        put :update, {:id => endereco.to_param, :endereco => valid_attributes}, valid_session
        assigns(:endereco).should eq(endereco)
      end

      it "redirects to the endereco" do
        endereco = Endereco.create! valid_attributes
        put :update, {:id => endereco.to_param, :endereco => valid_attributes}, valid_session
        response.should redirect_to(endereco)
      end
    end

    describe "with invalid params" do
      it "assigns the endereco as @endereco" do
        endereco = Endereco.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Endereco.any_instance.stub(:save).and_return(false)
        put :update, {:id => endereco.to_param, :endereco => {}}, valid_session
        assigns(:endereco).should eq(endereco)
      end

      it "re-renders the 'edit' template" do
        endereco = Endereco.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Endereco.any_instance.stub(:save).and_return(false)
        put :update, {:id => endereco.to_param, :endereco => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested endereco" do
      endereco = Endereco.create! valid_attributes
      expect {
        delete :destroy, {:id => endereco.to_param}, valid_session
      }.to change(Endereco, :count).by(-1)
    end

    it "redirects to the enderecos list" do
      endereco = Endereco.create! valid_attributes
      delete :destroy, {:id => endereco.to_param}, valid_session
      response.should redirect_to(enderecos_url)
    end
  end

end
