require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SecaosController do

  # This should return the minimal set of attributes required to create a valid
  # Secao. As you add validations to Secao, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SecaosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all secaos as @secaos" do
      secao = Secao.create! valid_attributes
      get :index, {}, valid_session
      assigns(:secaos).should eq([secao])
    end
  end

  describe "GET show" do
    it "assigns the requested secao as @secao" do
      secao = Secao.create! valid_attributes
      get :show, {:id => secao.to_param}, valid_session
      assigns(:secao).should eq(secao)
    end
  end

  describe "GET new" do
    it "assigns a new secao as @secao" do
      get :new, {}, valid_session
      assigns(:secao).should be_a_new(Secao)
    end
  end

  describe "GET edit" do
    it "assigns the requested secao as @secao" do
      secao = Secao.create! valid_attributes
      get :edit, {:id => secao.to_param}, valid_session
      assigns(:secao).should eq(secao)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Secao" do
        expect {
          post :create, {:secao => valid_attributes}, valid_session
        }.to change(Secao, :count).by(1)
      end

      it "assigns a newly created secao as @secao" do
        post :create, {:secao => valid_attributes}, valid_session
        assigns(:secao).should be_a(Secao)
        assigns(:secao).should be_persisted
      end

      it "redirects to the created secao" do
        post :create, {:secao => valid_attributes}, valid_session
        response.should redirect_to(Secao.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved secao as @secao" do
        # Trigger the behavior that occurs when invalid params are submitted
        Secao.any_instance.stub(:save).and_return(false)
        post :create, {:secao => {}}, valid_session
        assigns(:secao).should be_a_new(Secao)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Secao.any_instance.stub(:save).and_return(false)
        post :create, {:secao => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested secao" do
        secao = Secao.create! valid_attributes
        # Assuming there are no other secaos in the database, this
        # specifies that the Secao created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Secao.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => secao.to_param, :secao => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested secao as @secao" do
        secao = Secao.create! valid_attributes
        put :update, {:id => secao.to_param, :secao => valid_attributes}, valid_session
        assigns(:secao).should eq(secao)
      end

      it "redirects to the secao" do
        secao = Secao.create! valid_attributes
        put :update, {:id => secao.to_param, :secao => valid_attributes}, valid_session
        response.should redirect_to(secao)
      end
    end

    describe "with invalid params" do
      it "assigns the secao as @secao" do
        secao = Secao.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Secao.any_instance.stub(:save).and_return(false)
        put :update, {:id => secao.to_param, :secao => {}}, valid_session
        assigns(:secao).should eq(secao)
      end

      it "re-renders the 'edit' template" do
        secao = Secao.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Secao.any_instance.stub(:save).and_return(false)
        put :update, {:id => secao.to_param, :secao => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested secao" do
      secao = Secao.create! valid_attributes
      expect {
        delete :destroy, {:id => secao.to_param}, valid_session
      }.to change(Secao, :count).by(-1)
    end

    it "redirects to the secaos list" do
      secao = Secao.create! valid_attributes
      delete :destroy, {:id => secao.to_param}, valid_session
      response.should redirect_to(secaos_url)
    end
  end

end
