require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VotosUrnasController do

  # This should return the minimal set of attributes required to create a valid
  # VotosUrna. As you add validations to VotosUrna, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VotosUrnasController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all votos_urnas as @votos_urnas" do
      votos_urna = VotosUrna.create! valid_attributes
      get :index, {}, valid_session
      assigns(:votos_urnas).should eq([votos_urna])
    end
  end

  describe "GET show" do
    it "assigns the requested votos_urna as @votos_urna" do
      votos_urna = VotosUrna.create! valid_attributes
      get :show, {:id => votos_urna.to_param}, valid_session
      assigns(:votos_urna).should eq(votos_urna)
    end
  end

  describe "GET new" do
    it "assigns a new votos_urna as @votos_urna" do
      get :new, {}, valid_session
      assigns(:votos_urna).should be_a_new(VotosUrna)
    end
  end

  describe "GET edit" do
    it "assigns the requested votos_urna as @votos_urna" do
      votos_urna = VotosUrna.create! valid_attributes
      get :edit, {:id => votos_urna.to_param}, valid_session
      assigns(:votos_urna).should eq(votos_urna)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new VotosUrna" do
        expect {
          post :create, {:votos_urna => valid_attributes}, valid_session
        }.to change(VotosUrna, :count).by(1)
      end

      it "assigns a newly created votos_urna as @votos_urna" do
        post :create, {:votos_urna => valid_attributes}, valid_session
        assigns(:votos_urna).should be_a(VotosUrna)
        assigns(:votos_urna).should be_persisted
      end

      it "redirects to the created votos_urna" do
        post :create, {:votos_urna => valid_attributes}, valid_session
        response.should redirect_to(VotosUrna.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved votos_urna as @votos_urna" do
        # Trigger the behavior that occurs when invalid params are submitted
        VotosUrna.any_instance.stub(:save).and_return(false)
        post :create, {:votos_urna => {}}, valid_session
        assigns(:votos_urna).should be_a_new(VotosUrna)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        VotosUrna.any_instance.stub(:save).and_return(false)
        post :create, {:votos_urna => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested votos_urna" do
        votos_urna = VotosUrna.create! valid_attributes
        # Assuming there are no other votos_urnas in the database, this
        # specifies that the VotosUrna created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        VotosUrna.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => votos_urna.to_param, :votos_urna => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested votos_urna as @votos_urna" do
        votos_urna = VotosUrna.create! valid_attributes
        put :update, {:id => votos_urna.to_param, :votos_urna => valid_attributes}, valid_session
        assigns(:votos_urna).should eq(votos_urna)
      end

      it "redirects to the votos_urna" do
        votos_urna = VotosUrna.create! valid_attributes
        put :update, {:id => votos_urna.to_param, :votos_urna => valid_attributes}, valid_session
        response.should redirect_to(votos_urna)
      end
    end

    describe "with invalid params" do
      it "assigns the votos_urna as @votos_urna" do
        votos_urna = VotosUrna.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VotosUrna.any_instance.stub(:save).and_return(false)
        put :update, {:id => votos_urna.to_param, :votos_urna => {}}, valid_session
        assigns(:votos_urna).should eq(votos_urna)
      end

      it "re-renders the 'edit' template" do
        votos_urna = VotosUrna.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VotosUrna.any_instance.stub(:save).and_return(false)
        put :update, {:id => votos_urna.to_param, :votos_urna => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested votos_urna" do
      votos_urna = VotosUrna.create! valid_attributes
      expect {
        delete :destroy, {:id => votos_urna.to_param}, valid_session
      }.to change(VotosUrna, :count).by(-1)
    end

    it "redirects to the votos_urnas list" do
      votos_urna = VotosUrna.create! valid_attributes
      delete :destroy, {:id => votos_urna.to_param}, valid_session
      response.should redirect_to(votos_urnas_url)
    end
  end

end
